import { createId } from '@paralleldrive/cuid2';
import { index, integer, pgTable, text, timestamp } from 'drizzle-orm/pg-core';

export type CarrierInvitationStatus = 'pending' | 'redeemed' | 'expired';

/**
 * Auto-detected from active fuel card count at invite time (octane.stg_cmp_card via DWH — no
 * explicit "company type" field exists in servercrm/DWH, but card count is a clean real-world
 * proxy: 1 card = the owner drives it themself, 2+ = they're managing a fleet of drivers).
 * Null when undetermined (application-only invite, carrier id not populated yet).
 */
export type CarrierCompanyType = 'owner-operator' | 'fleet-manager';

/**
 * carrier_invitations — a Telegram deep-link invite for an owner OR a driver, generated by an
 * admin and opened via https://t.me/<bot>?start=<id>. Deliberately separate from `carrier_users`:
 * no login/password exists until the bot's mini-app actually redeems the invite (future work) —
 * this table only carries what the mini-app needs to identify the carrier at redemption time.
 * Drivers no longer need an existing owner carrier_users row to attach to (that concept only
 * made sense when owners were logins too) — a driver invite is just carrierId + cardId, the
 * shared carrierId is what implies "same fleet".
 *
 * `id` IS the Telegram start-param token: Telegram restricts start params to [A-Za-z0-9_-] and
 * 64 chars, which rules out embedding a signed JWT (dots + real company-name length blow the
 * budget) — a short opaque id backed by this row is the only viable mechanism.
 */
export const carrierInvitations = pgTable(
  'carrier_invitations',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => createId()),
    tenantId: text('tenant_id').notNull(),
    profile: text('profile').$type<'owner' | 'driver'>().notNull().default('owner'),
    carrierId: text('carrier_id'),
    applicationId: text('application_id'),
    companyName: text('company_name'),
    /** Driver only: the one fuel card this invite is for (must be an ACTIVE card; one driver per card). */
    cardId: text('card_id'),
    /** Driver only: the driver's name, entered by whoever created the invite (owner/admin/agent). */
    driverName: text('driver_name'),
    /** Owner only — a driver invite doesn't need this (one specific card is already known). */
    companyType: text('company_type').$type<CarrierCompanyType>(),
    /** Active fuel card count at invite time — the raw number companyType was derived from. */
    cardCount: integer('card_count'),
    agentName: text('agent_name'),
    agentZohoUserId: text('agent_zoho_user_id'),
    status: text('status').$type<CarrierInvitationStatus>().notNull().default('pending'),
    /** Set once the bot/mini-app redeems the invite into a real carrier_users row (future work). */
    redeemedCarrierUserId: text('redeemed_carrier_user_id'),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    tenantIdx: index('carrier_invitations_tenant_idx').on(table.tenantId),
    carrierIdx: index('carrier_invitations_tenant_carrier_idx').on(table.tenantId, table.carrierId),
  }),
);

export type CarrierInvitation = typeof carrierInvitations.$inferSelect;
export type NewCarrierInvitation = typeof carrierInvitations.$inferInsert;
