import { createId } from '@paralleldrive/cuid2';
import {
  doublePrecision,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

// NOTE: no DB foreign keys by design — isolation + integrity live in the repo layer
// (see CLAUDE.md), and keeping schema files free of value-level sibling imports lets
// drizzle-kit load each file individually.

/**
 * The phase ladder a case moves through. 'sales' — the deal owner gets the first window
 * (2 business days in the future workflow) to re-engage; 'retention' — the Retention desk
 * works the case; 'open_pool' — released for other agents to claim; 'citi' — final phase,
 * no further outreach.
 */
export type RetentionPhase = 'sales' | 'retention' | 'open_pool' | 'citi';

/** Workflow stage classification (Retention SOP step 3) — how/when the rep contacts. */
export type RetentionStage =
  | 'inactive_no_reason'
  | 'inactive_reason_noted'
  | 'out_of_reach'
  | 'pending'
  | 'assigned_to_agent';

/** Transaction-frequency class from the last 90 days (expected cadence: 2 / 5 / 7 days). */
export type FrequencyClass = 'high' | 'medium' | 'low';

/** Final disposition recorded when a case closes (SOP step 7 + flowchart branch 1). */
export type RetentionOutcome =
  | 'returned'
  | 'saved'
  | 'refused_offer'
  | 'out_of_business'
  | 'no_response'
  | 'lost';

export type RetentionCaseStatus = 'open' | 'closed';

/** Open Pool request lifecycle for a case sitting in the 'open_pool' phase (SOP step 9). */
export type PoolAssignment = 'available' | 'requested' | 'assigned' | 'rejected';

/**
 * retention_cases — the single Retention entity: one row per at-risk carrier episode.
 * Everything the workflow needs (phase, stage, frequency metrics, inactivity reason,
 * open-pool state, outcome) lives on this row; there are no satellite tables.
 *
 * Rows are AUTO-GENERATED by the DWH frequency-breach sync (octane.mart_transaction_line_items
 * + octane.dim_company; debtors excluded at the source) and can also be created manually.
 * One OPEN case per (tenant, carrier) — enforced by a partial unique index; a carrier that
 * relapses after a close gets a fresh row, preserving episode history.
 */
export const retentionCases = pgTable(
  'retention_cases',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => `rc_${createId()}`),
    tenantId: text('tenant_id').notNull(),

    // ---- client identity (denormalized from the DWH at generation time) ----
    /** The carrier company id (DWH/EFS) — the natural key of a case. */
    carrierId: text('carrier_id').notNull(),
    companyName: text('company_name'),
    applicationId: text('application_id'),
    /** The Octane sales agent (deal owner) — first line of contact in the sales phase. */
    agentName: text('agent_name'),
    agentZohoUserId: text('agent_zoho_user_id'),

    // ---- workflow position ----
    phase: text('phase').$type<RetentionPhase>().notNull().default('sales'),
    phaseChangedAt: timestamp('phase_changed_at', { withTimezone: true }).notNull().defaultNow(),
    stage: text('stage').$type<RetentionStage>().notNull().default('inactive_no_reason'),
    status: text('status').$type<RetentionCaseStatus>().notNull().default('open'),
    outcome: text('outcome').$type<RetentionOutcome>(),
    closedAt: timestamp('closed_at', { withTimezone: true }),

    // ---- why the client went quiet ----
    /** Categorized bucket (vacation, low_discounts, payment_issues, …) — free-form slug. */
    inactivityReason: text('inactivity_reason'),
    reasonNote: text('reason_note'),
    /** Out-of-reach contact attempts (flowchart branch 4: 5 attempts → open pool). */
    outOfReachAttempts: integer('out_of_reach_attempts').notNull().default(0),

    // ---- frequency-breach metrics (refreshed by every sync run) ----
    frequencyClass: text('frequency_class').$type<FrequencyClass>(),
    /** Expected max days between transactions for the class (2 / 5 / 7). */
    thresholdDays: integer('threshold_days'),
    lastTransactionAt: timestamp('last_transaction_at', { withTimezone: true }),
    daysInactive: integer('days_inactive'),
    txCount90d: integer('tx_count_90d'),
    gallons90d: doublePrecision('gallons_90d'),
    activeCards: integer('active_cards'),

    // ---- open pool (only meaningful while phase = 'open_pool') ----
    poolAssignment: text('pool_assignment').$type<PoolAssignment>(),
    poolTakenBy: text('pool_taken_by'),

    // ---- provenance ----
    source: text('source').$type<'auto' | 'manual'>().notNull().default('auto'),
    lastSyncedAt: timestamp('last_synced_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    /** One OPEN episode per carrier; closed history rows are unconstrained. */
    openCarrierUnique: uniqueIndex('retention_cases_tenant_carrier_open_uk')
      .on(table.tenantId, table.carrierId)
      .where(sql`${table.status} = 'open'`),
    phaseIdx: index('retention_cases_tenant_phase_idx').on(table.tenantId, table.phase),
    statusIdx: index('retention_cases_tenant_status_idx').on(table.tenantId, table.status),
    carrierIdx: index('retention_cases_tenant_carrier_idx').on(table.tenantId, table.carrierId),
  }),
);

export type RetentionCase = typeof retentionCases.$inferSelect;
export type NewRetentionCase = typeof retentionCases.$inferInsert;
