#!/usr/bin/env bash
#
# One-command local run: installs whatever is missing, provisions the web app's
# .env.local from the root .env, frees the pinned ports (3001 api / 5173 web —
# Vite runs with strictPort, so 5173 is ALWAYS 5173, never 5174), then starts
# the backend and the frontend together. Ctrl-C stops both.
#
#   pnpm dev:all      (or: bash scripts/dev-local.sh)
#
set -euo pipefail
cd "$(dirname "$0")/.."

if command -v pnpm >/dev/null 2>&1; then PNPM="pnpm"; else PNPM="corepack pnpm"; fi

API_PORT=3001
WEB_PORT=5173

# ── 1. Dependencies — ALWAYS sync (fast no-op when the lockfile is unchanged). ─
# A bare "node_modules exists" check rots: a pull that adds a dependency keeps serving
# code whose packages were never installed (vite: "Failed to resolve import …").
# CI=1: pnpm 11 may otherwise prompt "reinstall from scratch?" and abort in non-TTY.
echo "[setup] syncing deps…"
CI=1 $PNPM install --prefer-offline
CI=1 $PNPM -C apps/mytrion-crm install --prefer-offline

# ── 2. Web env: point the app at the local API with the dev key + mock auth ──
if [ ! -f apps/mytrion-crm/.env.local ]; then
  API_KEY_VALUE="$(grep -m1 '^API_KEY=' .env | cut -d= -f2- || true)"
  cat > apps/mytrion-crm/.env.local <<ENV
# Generated by scripts/dev-local.sh — local dev against the local backend.
VITE_API_URL=http://localhost:${API_PORT}
VITE_API_KEY=${API_KEY_VALUE}
# Access is Zoho-auth only (no mock bypass). For a temporary local bypass while
# developing UI, add: VITE_DEV_MOCK_AUTH=1 (dev builds only; compiled out of prod).
ENV
  echo "[setup] wrote apps/mytrion-crm/.env.local (Zoho auth required — real sign-in flow)"
fi

# ── 3. Free the pinned ports (stale dev servers from a previous run) ─────────
for port in $API_PORT $WEB_PORT; do
  pids="$(lsof -ti tcp:"$port" || true)"
  if [ -n "$pids" ]; then
    echo "[setup] port $port is busy — stopping stale process(es): $pids"
    kill $pids 2>/dev/null || true
    sleep 1
    # Still alive? Force it — the port must be ours (strictPort would otherwise fail).
    pids="$(lsof -ti tcp:"$port" || true)"
    [ -n "$pids" ] && kill -9 $pids 2>/dev/null || true
  fi
done

# ── 4. Run tunnel + both servers; stop all on exit ───────────────────────────
cleanup() {
  echo ""
  echo "[dev] shutting down…"
  kill "${BACK_PID:-}" "${FRONT_PID:-}" "${TUNNEL_PID:-}" 2>/dev/null || true
  wait "${BACK_PID:-}" "${FRONT_PID:-}" "${TUNNEL_PID:-}" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

# CMP MySQL tunnel (auto-reconnect; a no-op if MYSQL_SSH_* / the key aren't set, so DWH-only
# setups are unaffected). Keeps Admin → CMP Database working without a manual ssh.
bash scripts/db-tunnel.sh &
TUNNEL_PID=$!

$PNPM dev &
BACK_PID=$!
$PNPM -C apps/mytrion-crm dev &
FRONT_PID=$!

sleep 2
echo ""
echo "────────────────────────────────────────────────────────"
echo "  Mytrion Ops local dev"
echo "    API   →  http://localhost:${API_PORT}   (health: /health)"
echo "    Web   →  http://localhost:${WEB_PORT}   (admin: /m/admin)"
echo "  Ctrl-C stops both."
echo "────────────────────────────────────────────────────────"
echo ""

wait
