/**
 * servercrm agent-API touchpoints — the /api/agent/dwh/* data reads (balance, overview,
 * money code, cards, transactions, payment info) and /api/agent/activity/*. Path
 * placeholders {x} are filled from params; leftovers go to the query (GET) / body (POST).
 */
import { z } from 'zod';
import type { Touchpoint } from '../types.js';
import { carrierId, cardNumber, idString, limit, rangeKeyword, shortText, ymdDate } from './common.js';

const carrierOnly = z.object({ carrierId });

export const serverCrmAgentTouchpoints: Touchpoint[] = [
  {
    kind: 'servercrm',
    key: 'dwh.carrier_balance',
    title: 'Carrier balance (LOC / prepay, live EFS)',
    riskClass: 'read',
    carrierParam: 'carrierId',
    method: 'GET',
    pathTemplate: '/api/agent/dwh/carrier-balance/{carrierId}',
    paramsSchema: carrierOnly,
  },
  {
    kind: 'servercrm',
    key: 'dwh.carrier_overview',
    title: 'Carrier overview (balance + debt + cards)',
    riskClass: 'read',
    carrierParam: 'carrierId',
    method: 'GET',
    pathTemplate: '/api/agent/dwh/carrier-overview/{carrierId}',
    paramsSchema: carrierOnly,
  },
  {
    kind: 'servercrm',
    key: 'dwh.money_code',
    title: 'Money code preview (limit / drawn / available)',
    riskClass: 'read',
    carrierParam: 'carrierId',
    method: 'GET',
    pathTemplate: '/api/agent/dwh/money-code/{carrierId}',
    paramsSchema: carrierOnly,
  },
  {
    kind: 'servercrm',
    key: 'dwh.money_code_draw',
    title: 'Draw a money code',
    riskClass: 'destructive',
    carrierParam: 'carrierId',
    agentNameParam: 'requestedBy',
    method: 'POST',
    pathTemplate: '/api/agent/dwh/money-code/draw',
    paramsSchema: z.object({
      carrierId,
      amount: z.coerce.number().positive(),
      requestedBy: shortText(200).optional(),
      moneycode_reason: shortText(500),
    }),
  },
  {
    kind: 'servercrm',
    key: 'dwh.cards',
    title: 'Carrier cards (DWH)',
    riskClass: 'read',
    carrierParam: 'carrierId',
    method: 'GET',
    pathTemplate: '/api/agent/dwh/cards/{carrierId}',
    paramsSchema: carrierOnly,
  },
  {
    kind: 'servercrm',
    key: 'dwh.card_efs',
    title: 'Single card live EFS lookup',
    riskClass: 'read',
    carrierParam: 'carrierId',
    method: 'GET',
    pathTemplate: '/api/agent/dwh/cards/{carrierId}/{cardNumber}/efs',
    paramsSchema: z.object({ carrierId, cardNumber }),
  },
  {
    kind: 'servercrm',
    key: 'dwh.card_activate',
    title: 'Activate a card (EFS echo-back)',
    riskClass: 'write',
    carrierParam: 'carrierId',
    method: 'POST',
    pathTemplate: '/api/agent/dwh/cards/{carrierId}/{cardNumber}/activate',
    paramsSchema: z.object({ carrierId, cardNumber }),
  },
  {
    kind: 'servercrm',
    key: 'dwh.cards_last_used',
    title: 'Cards last-used report',
    riskClass: 'read',
    carrierParam: 'carrierId',
    method: 'GET',
    pathTemplate: '/api/agent/dwh/cards/{carrierId}/last-used',
    paramsSchema: z.object({ carrierId, range: rangeKeyword.default('all_time') }),
  },
  {
    kind: 'servercrm',
    key: 'dwh.transactions',
    title: 'Transactions (DWH line items)',
    riskClass: 'read',
    carrierParam: 'carrierId',
    method: 'GET',
    pathTemplate: '/api/agent/dwh/transactions/{carrierId}',
    paramsSchema: z.object({
      carrierId,
      range: rangeKeyword.optional(),
      limit: limit(5000, 5000).optional(),
      from: ymdDate.optional(),
      to: ymdDate.optional(),
    }),
  },
  {
    kind: 'servercrm',
    key: 'dwh.transaction_invoices',
    title: 'Transaction → invoice refs',
    riskClass: 'read',
    carrierParam: 'carrierId',
    method: 'GET',
    pathTemplate: '/api/agent/dwh/transactions/{carrierId}/invoices',
    paramsSchema: z.object({
      carrierId,
      range: rangeKeyword.optional(),
      from: ymdDate.optional(),
      to: ymdDate.optional(),
    }),
  },
  {
    kind: 'servercrm',
    key: 'dwh.payment_info',
    title: 'Payment info (invoices + payments window)',
    riskClass: 'read',
    carrierParam: 'carrierId',
    method: 'GET',
    pathTemplate: '/api/agent/dwh/payment-info/{carrierId}',
    paramsSchema: z.object({ carrierId, days: z.coerce.number().int().min(1).max(365).default(90) }),
  },
  {
    kind: 'servercrm',
    key: 'activity.agent',
    title: 'Agent activity KPIs',
    riskClass: 'read',
    identityParam: 'zohoUserId',
    agentNameParam: 'agentName',
    method: 'GET',
    pathTemplate: '/api/agent/activity/{zohoUserId}',
    paramsSchema: z.object({
      zohoUserId: idString.optional(),
      range: z.string().max(40).optional(),
      agentName: shortText(200).optional(),
    }),
  },
  {
    kind: 'servercrm',
    key: 'activity.leaderboard',
    title: 'Agent activity leaderboard',
    riskClass: 'read',
    agentNameParam: 'agentName',
    method: 'GET',
    pathTemplate: '/api/agent/activity/leaderboard',
    paramsSchema: z.object({
      range: z.string().max(40).optional(),
      limit: limit(100, 20).optional(),
      metric: z.string().max(40).optional(),
      agentName: shortText(200).optional(),
    }),
  },
];
