/**
 * servercrm misc touchpoints — EFS live actions, fraud release, WEX applications, carrier
 * prospect search, salesMytrion invoices, and the /api/clients/* client-detail reads.
 */
import { z } from 'zod';
import type { Touchpoint } from '../types.js';
import { carrierId, cardNumber, idString, limit, SALES, salesRange, shortText, ymdDate } from './common.js';

export const serverCrmMiscTouchpoints: Touchpoint[] = [
  {
    kind: 'servercrm',
    key: 'efs.cards',
    title: 'Live EFS card list (fraud-hold statuses)',
    riskClass: 'read',
    departments: SALES,
    carrierParam: 'carrierId',
    method: 'POST', // servercrm models this read as a POST
    pathTemplate: '/api/efs/cards',
    paramsSchema: z.object({ carrierId }),
  },
  {
    kind: 'servercrm',
    key: 'efs.card_info',
    title: 'Update card unit / driver info (EFS)',
    riskClass: 'write',
    departments: SALES,
    carrierParam: 'carrierId',
    method: 'POST',
    pathTemplate: '/api/efs/card/info',
    paramsSchema: z
      .object({
        carrierId,
        cardNumber,
        unitNumber: shortText(40).optional(),
        driverId: shortText(40).optional(),
        driverName: shortText(200).optional(),
      })
      .refine((v) => v.unitNumber || v.driverId || v.driverName, {
        message: 'Provide at least one of unitNumber, driverId, driverName',
      }),
  },
  {
    kind: 'servercrm',
    key: 'efs.card_override',
    title: 'Fraud-hold override (~30 min card unlock)',
    riskClass: 'destructive',
    departments: SALES,
    carrierParam: 'carrierId',
    method: 'POST',
    pathTemplate: '/api/efs/card/override',
    paramsSchema: z.object({ carrierId, cardNumber }),
  },
  {
    kind: 'servercrm',
    key: 'fraud.hold_release',
    title: 'Fraud hold / release request (routes to fraud team)',
    riskClass: 'destructive',
    departments: SALES,
    carrierParam: 'carrierId',
    method: 'POST',
    pathTemplate: '/api/fraud/hold-release',
    paramsSchema: z.object({
      companyName: shortText(300),
      carrierId,
      agentEmail: z.string().email().max(200),
      ticketType: z.enum(['fraud_hold', 'fraud_release']).default('fraud_release'),
      cardNumber,
    }),
  },
  {
    kind: 'servercrm',
    key: 'wex.application',
    title: 'WEX application status',
    riskClass: 'read',
    departments: SALES,
    method: 'GET',
    pathTemplate: '/api/wex/application/{appId}',
    paramsSchema: z.object({ appId: idString }),
  },
  {
    kind: 'servercrm',
    key: 'wex.applications_search',
    title: 'WEX application search',
    riskClass: 'read',
    departments: SALES,
    method: 'GET',
    pathTemplate: '/api/wex/applications/search',
    paramsSchema: z.object({
      appId: idString.optional(),
      firstName: shortText(100).optional(),
      lastName: shortText(100).optional(),
      company: shortText(300).optional(),
      email: z.string().max(200).optional(),
      phone: shortText(30).optional(),
      mc: shortText(30).optional(),
      dot: shortText(30).optional(),
    }),
  },
  {
    kind: 'servercrm',
    key: 'sales.carriers_search',
    title: 'Carrier prospect search (broker snapshot)',
    riskClass: 'read',
    departments: SALES,
    method: 'POST',
    pathTemplate: '/api/sales/carriers/search',
    // Widget fetch window is 200 or 500 — don't cap below what the UI offers.
    paramsSchema: z.object({ query: shortText(300), limit: limit(500, 200).optional() }),
  },
  {
    kind: 'servercrm',
    key: 'sales_mytrion.fetch_invoices',
    title: 'Sales invoices (DWH)',
    riskClass: 'read',
    departments: SALES,
    carrierParam: 'carrierId',
    method: 'GET',
    pathTemplate: '/api/salesMytrion/fetchInvoices',
    paramsSchema: z.object({
      carrierId,
      range: salesRange.optional(),
      status: z.string().max(40).optional(),
      from: ymdDate.optional(),
      to: ymdDate.optional(),
    }),
  },
  {
    kind: 'servercrm',
    key: 'sales_mytrion.invoice_signed_url',
    title: 'Invoice download link (2-min signed URL)',
    riskClass: 'read',
    departments: SALES,
    method: 'GET',
    pathTemplate: '/api/salesMytrion/invoices/{invoiceId}/signed-url',
    paramsSchema: z.object({ invoiceId: idString, type: z.enum(['pdf', 'excel']).default('pdf') }),
  },
  {
    kind: 'servercrm',
    key: 'clients.by_agent',
    title: 'Client roster by agent (with CMP debt)',
    riskClass: 'read',
    departments: SALES,
    identityParam: 'zohoUserId',
    agentNameParam: 'agentName',
    method: 'GET',
    pathTemplate: '/api/clients/by-agent/{zohoUserId}',
    paramsSchema: z.object({
      zohoUserId: idString.optional(),
      agentName: shortText(200).optional(),
    }),
  },
  {
    kind: 'servercrm',
    key: 'clients.invoices',
    title: 'Client invoices (CMP, DWH fallback)',
    riskClass: 'read',
    departments: SALES,
    carrierParam: 'carrierId',
    method: 'GET',
    pathTemplate: '/api/clients/{carrierId}/invoices',
    paramsSchema: z.object({ carrierId, limit: limit(500, 100).optional() }),
  },
  {
    kind: 'servercrm',
    key: 'clients.payment_transactions',
    title: 'Client payment transactions (all sources)',
    riskClass: 'read',
    departments: SALES,
    carrierParam: 'carrierId',
    method: 'GET',
    pathTemplate: '/api/clients/{carrierId}/payment-transactions',
    paramsSchema: z.object({ carrierId, limit: limit(500, 100).optional() }),
  },
  {
    kind: 'servercrm',
    key: 'clients.recent_transactions',
    title: 'Client recent fuel transactions',
    riskClass: 'read',
    departments: SALES,
    carrierParam: 'carrierId',
    method: 'GET',
    pathTemplate: '/api/clients/{carrierId}/recent-transactions',
    paramsSchema: z.object({ carrierId, limit: limit(200, 30).optional() }),
  },
];
