/**
 * Octane tools for the OpenAI session — thin, paranoid pipes to mytrion /v1/support-bot/*.
 * RBAC lives SERVER-SIDE (role from registration, carrier must match); here we only
 * (a) bind the carrier per chat (closure — never a model argument) and (b) verify the
 * claimed asker actually spoke in this chat recently (the gateway saw every message,
 * so this check is authoritative, not DB-heuristic like v1).
 */
import { z } from 'zod';
import { config } from './config.js';
import { searchSupportKb } from './kb/search.js';
import { clearButtons, sendButtons, sendMessage, setReaction } from './telegram.js';
import { logMessage } from './messageLog.js';
import { defineTool as tool, type ToolManifest } from './toolRuntime.js';
import { incrementCounter } from './metrics.js';
import { enabledServiceSummary } from './serviceRegistry.js';
import { backendErrorInfo, supportBotHeaders } from './octaneClient.js';
import {
  CONFIRMABLE_TOOL_NAMES,
  createConfirmation,
  newConfirmationToken,
} from './confirmations.js';
import { gatewayOperationKey, gatewaySessionKeyHash } from './operationIdentity.js';

/** chatId → (userId → last-seen ms). Filled by the poll loop for every inbound message. */
export const recentSenders = new Map<number, Map<number, number>>();
const RECENT_MS = 5 * 60_000;

export function noteSender(chatId: number, userId: number): void {
  let m = recentSenders.get(chatId);
  if (!m) recentSenders.set(chatId, (m = new Map()));
  m.set(userId, Date.now());
}

setInterval(() => {
  const cutoff = Date.now() - RECENT_MS;
  for (const [chatId, users] of recentSenders) {
    for (const [userId, seenAt] of users) {
      if (seenAt < cutoff) users.delete(userId);
    }
    if (!users.size) recentSenders.delete(chatId);
  }
}, RECENT_MS).unref();

function senderOk(chatId: number, userId: number): boolean {
  const ts = recentSenders.get(chatId)?.get(userId);
  return ts != null && Date.now() - ts <= RECENT_MS;
}

async function backend(
  path: string,
  payload: Record<string, unknown>,
  carrierId: string,
  extraHeaders: Readonly<Record<string, string>> = {},
) {
  const res = await fetch(`${config.octaneBase}/v1${path}`, {
    method: 'POST',
    headers: supportBotHeaders(true, extraHeaders),
    body: JSON.stringify({ carrierId, ...payload }),
    signal: AbortSignal.timeout(30_000),
  });
  const data = (await res.json().catch(() => ({}))) as Record<string, unknown>;
  if (!res.ok) {
    incrementCounter('backend_error_total');
    const error = backendErrorInfo(data, res.status);
    if (error.code === 'SUPPORT_BOT_IDEMPOTENCY_CONFLICT') {
      incrementCounter('idempotency_conflict_total');
    }
    return { error: true, status: res.status, ...error };
  }
  return data;
}

const asker = {
  telegram_user_id: z.number().describe('Telegram id of the MESSAGE SENDER who asked — never anyone else'),
};

const WRITE_TOOLS = new Set([
  'telegram_progress',
  'octane_txn_report',
  'octane_money_code',
  'octane_card_action',
  'octane_card_limits',
  'octane_card_info',
  'octane_card_lookup_report',
  'octane_invoice',
  'octane_invoices',
  'octane_balance_dm',
  'octane_manual_code',
  'octane_service_request',
  'telegram_buttons',
  'telegram_react',
  'octane_override',
]);

/** These state mutations require a Telegram callback generated by our own button UI. */
const TRUSTED_CONFIRMATION_TOOLS = new Set([
  'octane_money_code',
  'octane_card_action',
  'octane_card_limits',
  'octane_card_info',
  'octane_service_request',
  'octane_override',
]);

const BEST_EFFORT_TOOLS = new Set(['telegram_progress', 'telegram_react']);

const MUTATION_PATHS = new Map<string, string>([
  ['/support-bot/money-code/draw', 'money_code'],
  ['/support-bot/card-action', 'card_action'],
  ['/support-bot/card-limits', 'card_limits'],
  ['/support-bot/card-info', 'card_info'],
  ['/support-bot/service-request', 'service_request'],
  ['/support-bot/override', 'override'],
]);

/**
 * One registry per turn: carrierId and the verified Telegram asker are closed over. The model
 * cannot redirect a valid tool call to another recently-active member of the same group.
 */
export function buildOctaneTools(
  chatId: number,
  carrierId: string,
  askerId: number,
  turnId = `local:${chatId}:${askerId}:${Date.now()}`,
  confirmationId?: string,
): ToolManifest[] {
  const enabledServices = enabledServiceSummary().split(',').filter(Boolean);
  const sessionKeyHash = gatewaySessionKeyHash(
    config.environment,
    config.botIdentity,
    chatId,
    askerId,
  );
  let fencePromise: Promise<number | null> | null = null;
  let writeOccurrence = 0;
  const sessionFence = (): Promise<number | null> => {
    fencePromise ??= backend(
      '/support-bot/session-fence',
      { sessionKeyHash },
      carrierId,
    ).then((result) =>
      result['enabled'] === true ? Number(result['fencingToken']) : null,
    );
    return fencePromise;
  };
  const guard = (userId: number): string | null =>
    userId !== askerId
      ? 'refused: telegram_user_id does not match the current message sender'
      : senderOk(chatId, userId)
        ? null
        : 'refused: that user has not sent a recent message in this chat';
  const run = async (path: string, userId: number, extra: Record<string, unknown> = {}) => {
    const g = guard(userId);
    if (g) return { content: [{ type: 'text' as const, text: g }], isError: true };
    const payload = { telegramUserId: String(userId), ...extra };
    const operationType = MUTATION_PATHS.get(path);
    let headers: Record<string, string> = {};
    if (operationType) {
      const fencingToken = await sessionFence();
      if (fencingToken == null && config.nodeEnv === 'production') {
        throw new Error('support-bot idempotency is not enabled on the backend');
      }
      if (fencingToken != null) {
        const occurrence = writeOccurrence;
        writeOccurrence += 1;
        headers = {
          'Idempotency-Key': gatewayOperationKey({
            environment: config.environment,
            botIdentity: config.botIdentity,
            turnId,
            writeOccurrence: occurrence,
            tenantId: config.tenantId,
            carrierId,
            telegramUserId: askerId,
            operationType,
            arguments: payload,
          }),
          ...(confirmationId
            ? { 'X-Support-Bot-Confirmation-Id': confirmationId }
            : {}),
          'X-Support-Bot-Turn-Id': turnId,
          'X-Support-Bot-Write-Occurrence': String(occurrence),
          'X-Support-Bot-Session-Key': sessionKeyHash,
          'X-Support-Bot-Fencing-Token': String(fencingToken),
        };
      }
    }
    const data = await backend(path, payload, carrierId, headers);
    if (data['replayed'] === true) incrementCounter('write_replayed_total');
    return { content: [{ type: 'text' as const, text: JSON.stringify(data) }], isError: Boolean((data as { error?: boolean }).error) };
  };

  const tools: ToolManifest[] = [
      tool(
        'telegram_progress',
        "Send ONE short progress line to the group RIGHT NOW, before you continue working. Use when the task will take a while (report build, several lookups, a write chain): write it in the USER'S OWN language and name the task — e.g. \"Hisobotingizni tayyorlayapman — ~1 daqiqa\" / \"Готовлю отчёт — около минуты\". At most ONCE per request; never use it for the final answer.",
        { text: z.string().min(1).max(200) },
        async ({ text }) => {
          await sendMessage(chatId, text).catch(() => undefined);
          logMessage({
            ts: new Date().toISOString(),
            carrierId,
            chatId,
            userId: 0,
            name: 'bot',
            dir: 'out',
            text,
          });
          return { content: [{ type: 'text' as const, text: 'progress line sent — continue the task' }] };
        },
      ),
      tool('octane_whoami', "Is the sender a registered Octane mini-app user of this company, their role (owner/driver), and the carrier's sales agent (agentName) to hand off to when you can't resolve an ask? Call FIRST for any service ask.", asker, ({ telegram_user_id }) => run('/support-bot/whoami', telegram_user_id)),
      tool(
        'octane_kb_search',
        "FAST: search the enabled Octane client knowledge base for a FACTUAL 'how does X work' question — fees, supported stations, gallon limits, card operations, mini-app how-tos, and troubleshooting. Disabled-service articles are excluded. State facts ONLY from returned text or live octane_* tools; no match means a human must confirm. Client-safe content only.",
        { query: z.string().min(2).max(200).describe('the topic or the question to look up, in any language') },
        async ({ query }) => {
          const hits = await searchSupportKb(
            carrierId,
            query,
            enabledServices,
            3,
          );
          return { content: [{ type: 'text' as const, text: JSON.stringify(hits.length ? hits : { note: 'no KB match — do not guess; offer to escalate to the Octane agent' }) }] };
        },
      ),
      tool(
        'octane_card_status',
        "Card status across the WHOLE fleet (no blind window). ONE card (a PHOTO or 'check card X') → pass card_last6 for its exact status (fraudHold + overrideAvailable). Narrow a big fleet → query (matches last6/unit/driver, e.g. a driver name) and/or status ('active'|'inactive'|'hold', e.g. 'which cards are on hold'). Nothing → driver gets own card WITH gallon limits; owner gets the full fleet (up to 150) + active/hold counts.",
        { ...asker, card_last6: z.string().min(4).max(19).optional().describe('exact card to check — REQUIRED for a one-card / photo ask'), query: z.string().min(1).max(60).optional().describe('search last6 / unit / driver name'), status: z.enum(['active', 'inactive', 'hold']).optional().describe('filter the fleet by status') },
        ({ telegram_user_id, card_last6, query, status }) => run('/support-bot/card-status', telegram_user_id, { ...(card_last6 ? { cardLast6: card_last6 } : {}), ...(query ? { query } : {}), ...(status ? { status } : {}) }),
      ),
      tool('octane_funds', 'Does the account have funds? Driver gets yes/no only (never figures); owner gets balance figures.', asker, ({ telegram_user_id }) => run('/support-bot/funds', telegram_user_id)),
      tool(
        'octane_txn_report',
        "LONG (~1-3 min): build the asker's transaction report and send it to THEIR PRIVATE Octane bot chat (never this group). Driver: own card, retail. Owner: whole fleet, one card via card_last6, OR one exact unit via unit_number. Never claim a unit-scoped report unless unit_number was passed and the tool succeeded. ANNOUNCE FIRST via telegram_progress (ETA + 'DM'ga yuboraman'), and make your final reply the delivery confirmation.",
        {
          ...asker,
          range: z.enum(['day', 'week', 'month', 'quarter']).default('week'),
          from: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe('custom window start YYYY-MM-DD — use when they name exact dates'),
          to: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
          format: z.enum(['xlsx', 'pdf', 'csv']).default('xlsx'),
          card_last6: z.string().min(4).max(19).optional().describe('OWNER only: scope to one card; never combine with unit_number'),
          unit_number: z.string().trim().min(1).max(60).optional().describe('OWNER only: scope to one exact unit; never combine with card_last6'),
        },
        ({ telegram_user_id, range, from, to, format, card_last6, unit_number }) =>
          run('/support-bot/txn-report', telegram_user_id, {
            range,
            format,
            ...(from ? { from } : {}),
            ...(to ? { to } : {}),
            ...(card_last6 ? { cardLast6: card_last6 } : {}),
            ...(unit_number ? { unitNumber: unit_number } : {}),
          }),
      ),
      tool(
        'octane_money_code_quote',
        "FAST: how much money code the OWNER can draw RIGHT NOW + the fee for an amount. Call this when they ask 'qancha olsam bo'ladi?' and ALWAYS before octane_money_code to confirm the amount fits. Returns `available` (the server-computed limit — NEVER invent one) and, if you pass amount, the EFS fee ($3.50 per $500 + $0.75 per extra use) and whether it fits. Owner-only; amounts may be spoken to the owner.",
        { ...asker, amount: z.coerce.number().positive().optional().describe('optional — get the exact fee + whether it fits the limit') },
        ({ telegram_user_id, amount }) => run('/support-bot/money-code/preview', telegram_user_id, amount != null ? { amount } : {}),
      ),
      tool(
        'octane_money_code',
        'LONG (~1-2 min): issue an EFS money code (OWNER only, confirm amount+unit+reason first; check octane_money_code_quote so the amount fits the limit). The code goes to their PRIVATE Octane bot chat — never this group. After confirmation, announce via telegram_progress (ETA + delivery promise); final reply = delivery confirmation.',
        { ...asker, amount: z.number().positive(), unit_number: z.string().min(1).max(60), reason: z.string().min(1).max(120) },
        ({ telegram_user_id, amount, unit_number, reason }) => run('/support-bot/money-code/draw', telegram_user_id, { amount, unitNumber: unit_number, reason }),
      ),
      tool(
        'octane_card_action',
        "Activate or deactivate one of the OWNER's cards by its last digits (confirm first — this changes the card's state).",
        { ...asker, card_last6: z.string().min(4).max(19), action: z.enum(['activate', 'deactivate']) },
        ({ telegram_user_id, card_last6, action }) => run('/support-bot/card-action', telegram_user_id, { cardLast6: card_last6, action }),
      ),
      tool(
        'octane_card_limits',
        'Change a card daily gallon limit (OWNER, confirm first): diesel ULSD or DEF, increase/decrease by N gallons.',
        { ...asker, card_last6: z.string().min(4).max(19), limit_id: z.enum(['ULSD', 'DEFD']), action: z.enum(['increase', 'decrease']), value: z.number().positive() },
        ({ telegram_user_id, card_last6, limit_id, action, value }) => run('/support-bot/card-limits', telegram_user_id, { cardLast6: card_last6, limitId: limit_id, action, value }),
      ),
      tool(
        'octane_card_info',
        "Update a card's unit number / driver ID (drivers: their own card, no card_last6 needed) or driver name (owner only, with card_last6).",
        { ...asker, card_last6: z.string().min(4).max(19).optional(), unit_number: z.string().min(1).max(60).optional(), driver_id: z.string().min(1).max(60).optional(), driver_name: z.string().min(1).max(120).optional() },
        ({ telegram_user_id, card_last6, unit_number, driver_id, driver_name }) =>
          run('/support-bot/card-info', telegram_user_id, {
            ...(card_last6 ? { cardLast6: card_last6 } : {}),
            ...(unit_number ? { unitNumber: unit_number } : {}),
            ...(driver_id ? { driverId: driver_id } : {}),
            ...(driver_name ? { driverName: driver_name } : {}),
          }),
      ),
      tool(
        'octane_card_lookup_report',
        "Build the verified OWNER or MANAGER's live Card Lookup report and send it as PDF or Excel to their PRIVATE Octane bot chat. Use when they ask for a card list, card lookup, or fleet card report. Never send it to the group.",
        {
          ...asker,
          format: z.enum(['pdf', 'xlsx']).default('xlsx'),
        },
        ({ telegram_user_id, format }) =>
          run('/support-bot/card-lookup-report', telegram_user_id, { format }),
      ),
      tool(
        'octane_transactions',
        "Recent transactions INLINE (MEDIUM ~20-40s): one line per fueling — date, gallons, location, card last6. NO dollar amounts (by design — money never goes to the group); when they ask for amounts/totals, use octane_txn_report (file to their DM) instead. Driver: own card. Owner: fleet, or one card via card_last6.",
        { ...asker, range: z.enum(['day', 'week', 'month']).default('week'), card_last6: z.string().min(4).max(19).optional(), limit: z.number().int().positive().max(20).default(10) },
        ({ telegram_user_id, range, card_last6, limit }) =>
          run('/support-bot/transactions', telegram_user_id, { range, limit, ...(card_last6 ? { card_last6 } : {}) }),
      ),
      tool(
        'octane_invoice',
        "LONG (~1 min): send the OWNER's LATEST invoice document (PDF, or Excel when they ask) to their PRIVATE bot chat (never this group). Announce via telegram_progress first (ETA + 'DM'ga yuboraman'); final reply = delivery confirmation.",
        { ...asker, format: z.enum(['pdf', 'xlsx']).default('pdf').describe("'xlsx' when they ask for Excel") },
        ({ telegram_user_id, format }) => run('/support-bot/invoice', telegram_user_id, { format }),
      ),
      tool(
        'octane_invoices',
        "Invoice QUESTIONS (OWNER only, MEDIUM ~20-40s): 'qancha qarzim bor', 'invoicelar ro'yxati', a month's invoices. The AMOUNTS are sent to their PRIVATE bot chat automatically; the result gives you ONLY counts/statuses/dates — those are safe to say inline, dollar figures are NOT. Presets or exact from/to dates.",
        { ...asker, range: z.enum(['last_7', 'last_30', 'last_90', 'last_365', 'all_time']).default('last_90'), from: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe('custom window start — use when they name exact dates/months'), to: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional() },
        ({ telegram_user_id, range, from, to }) => run('/support-bot/invoices', telegram_user_id, { range, ...(from ? { from } : {}), ...(to ? { to } : {}) }),
      ),
      tool('octane_balance_dm', "LONG (~1 min): send the OWNER their balance FIGURES to their private Octane bot chat (figures never go in the group). Announce via telegram_progress first (ETA + 'DM'ga yuboraman'); final reply = delivery confirmation.", asker, ({ telegram_user_id }) => run('/support-bot/balance', telegram_user_id)),
      tool('octane_manual_code', "LONG (~1 min): send the asker's manual entry code (full card number) to their PRIVATE bot chat. Drivers: own card. Owners: give card_last6. Announce via telegram_progress first (ETA + delivery promise); final reply = delivery confirmation.", { ...asker, card_last6: z.string().min(4).max(19).optional() }, ({ telegram_user_id, card_last6 }) => run('/support-bot/manual-code', telegram_user_id, card_last6 ? { cardLast6: card_last6 } : {})),
      tool(
        'octane_service_request',
        "File a support ticket with Octane's team for supported workflows only: general-support (out-of-scope operational question or human CS handoff), maintenance-roadside, billing-form (owner), card-replace, card-fraud, account-reactivate (owner), dispute-txn, or request fallbacks (money-code, card-activate, card-limit, override-card). The bot has no callback/call-request service: never collect a phone number or create buttons for 'call me'. Gather the relevant details and confirm a concise summary first; include the user's words as the comment. Tell them the team will follow up only after a real ticket ID is returned.",
        {
          ...asker,
          request: z.enum(['general-support', 'maintenance-roadside', 'billing-form', 'card-replace', 'card-fraud', 'account-reactivate', 'dispute-txn', 'money-code', 'card-activate', 'card-limit', 'override-card']),
          comment: z.string().max(1500).describe("The user's own description of what they need"),
        },
        ({ telegram_user_id, request, comment }) => run('/support-bot/service-request', telegram_user_id, { request, comment }),
      ),
      tool('octane_tracking', "Where is the owner's card shipment? Owner-only tracking status.", asker, ({ telegram_user_id }) => run('/support-bot/tracking', telegram_user_id)),
      tool('octane_last_used', "When was a card last used? Driver: their own card. Owner: the whole fleet, or one card via card_last6. No dollar figures — safe to answer inline.", { ...asker, card_last6: z.string().min(4).max(19).optional().describe('OWNER: one card by last digits; omit for the fleet') }, ({ telegram_user_id, card_last6 }) => run('/support-bot/last-used', telegram_user_id, card_last6 ? { cardLast6: card_last6 } : {})),
      tool('octane_payment_status', "Owner billing-cycle & payment status — billing cycle, next due date, open/paid invoice counts, open balance. Owner-only. DOLLAR FIGURES go to the owner's PRIVATE chat only; in the group say status + dates, never amounts.", asker, ({ telegram_user_id }) => run('/support-bot/payment', telegram_user_id)),
      tool('octane_billing_form', "Show the OWNER their billing form + verification status (the same info the mini-app billing-form sheet shows). Owner-only. To SUBMIT/file a billing form for a service charge, use octane_service_request(billing-form) instead.", asker, ({ telegram_user_id }) => run('/support-bot/billing-form', telegram_user_id)),
      tool(
        'telegram_buttons',
        'Send the ONE trusted Yes/No confirmation required for a supported state-changing tool. Set confirmation.tool_name + its complete exact arguments (omit telegram_user_id; the gateway binds it); callback data is server-generated. Never use buttons to gather details, choose urgency, navigate services, request a call, or offer a generic handoff. Ask those questions as plain text. After calling this, output SILENT.',
        {
          text: z.string().min(1).max(500).describe("The message above the buttons, in the user's language"),
          confirmation: z
            .object({
              tool_name: z.enum(CONFIRMABLE_TOOL_NAMES),
              arguments: z.record(z.unknown()),
              confirm_label: z.string().min(1).max(40).default('✅ Ha'),
              cancel_label: z.string().min(1).max(40).default("❌ Yo'q"),
            })
            .describe('Exact supported state-changing action and args to bind'),
          reply_to_message_id: z.number().optional(),
        },
        async ({ text, confirmation, reply_to_message_id }) => {
          const target = tools.find((manifest) => manifest.name === confirmation.tool_name);
          if (!target || target.confirmationMode !== 'trusted_button') {
            return {
              content: [{ type: 'text' as const, text: 'invalid confirmation target' }],
              isError: true,
            };
          }
          const boundArguments = {
            ...confirmation.arguments,
            telegram_user_id: askerId,
          };
          const validated = target.validate?.(boundArguments);
          if (!validated) {
            return {
              content: [{ type: 'text' as const, text: 'confirmation target cannot be validated' }],
              isError: true,
            };
          }
          if (!validated.ok) {
            return {
              content: [
                {
                  type: 'text' as const,
                  text: `invalid confirmation arguments: ${validated.message}`,
                },
              ],
              isError: true,
            };
          }
          const refusal = target.authorize?.(validated.value);
          if (refusal) {
            return {
              content: [{ type: 'text' as const, text: `confirmation refused: ${refusal}` }],
              isError: true,
            };
          }
          const token = newConfirmationToken();
          const messageId = await sendButtons(
            chatId,
            text,
            [
              { label: confirmation.confirm_label, data: `c:${token}` },
              { label: confirmation.cancel_label, data: `x:${token}` },
            ],
            reply_to_message_id,
          );
          try {
            await createConfirmation({
              token,
              carrierId,
              chatId,
              telegramUserId: askerId,
              messageId,
              toolName: confirmation.tool_name,
              arguments: validated.value,
            });
          } catch (error) {
            await clearButtons(chatId, messageId);
            throw error;
          }
          logMessage({
            ts: new Date().toISOString(),
            carrierId,
            chatId,
            userId: 0,
            name: 'bot',
            dir: 'out',
            text,
          });
          return { content: [{ type: 'text' as const, text: 'buttons sent — now output SILENT and wait for the tap' }] };
        },
      ),
      tool(
        'telegram_react',
        "React to a message with an emoji instead of replying — the cheapest ack. Use for pure confirmations (👍 done, ✅ handled) when no words are needed; then output SILENT.",
        { message_id: z.number(), emoji: z.enum(['👍', '✅', '🔥', '🙏', '👌', '⚡']) },
        async ({ message_id, emoji }) => {
          await setReaction(chatId, message_id, emoji).catch(() => {});
          return { content: [{ type: 'text' as const, text: 'reacted' }] };
        },
      ),
      tool('octane_override', "Unlock the asking DRIVER's own held card for ~30 minutes. Only after their explicit yes to a confirm question.", asker, ({ telegram_user_id }) => run('/support-bot/override', telegram_user_id, { requestId: turnId })),
  ];

  return tools.map((manifest) => {
    const needsSenderCheck =
      manifest.name.startsWith('octane_') && manifest.name !== 'octane_kb_search';
    return {
      ...manifest,
      riskClass: WRITE_TOOLS.has(manifest.name) ? 'write' : 'read',
      ...(TRUSTED_CONFIRMATION_TOOLS.has(manifest.name)
        ? { confirmationMode: 'trusted_button' as const }
        : {}),
      ...(BEST_EFFORT_TOOLS.has(manifest.name)
        ? { requirementMode: 'best_effort' as const }
        : {}),
      ...(needsSenderCheck
        ? {
            authorize: (input: Record<string, unknown>): string | null => {
              const userId = input['telegram_user_id'];
              if (typeof userId !== 'number') return 'telegram_user_id is required';
              return guard(userId);
            },
          }
        : {}),
    };
  });
}
